"""Dirichlet-process measurement subclustering for extended-target prototypes.

The utilities in this module are intentionally local to a measurement subset.  A
caller such as a GLMB, PMBM, or multi-Bernoulli tracker can keep the RFS layer in
charge of target existence, labels, and target-to-measurement association, while
using this module to score or propose subclusters inside one candidate
extended-target measurement cell.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import log, pi

import numpy as np

_TEXT_SCALAR_TYPES = (str, bytes, bytearray, np.str_, np.bytes_)
_BOOL_SCALAR_TYPES = (bool, np.bool_)


def _as_finite_scalar(value: float, name: str) -> float:
    message = f"{name} must be a finite scalar"
    try:
        value_array = np.asarray(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(message) from exc
    if value_array.shape != () or value_array.dtype == np.bool_:
        raise ValueError(message)
    scalar = value_array.item()
    if isinstance(scalar, (*_BOOL_SCALAR_TYPES, *_TEXT_SCALAR_TYPES)):
        raise ValueError(message)
    try:
        result = float(scalar)
    except (TypeError, ValueError, OverflowError) as exc:
        raise ValueError(message) from exc
    if not np.isfinite(result):
        raise ValueError(message)
    return result


def _positive_finite_scalar(value: float, name: str) -> float:
    result = _as_finite_scalar(value, name)
    if result <= 0.0:
        raise ValueError(f"{name} must be positive")
    return result


def _integer_at_least(value: int | None, name: str, lower_bound: int) -> int | None:
    if value is None:
        return None
    message = f"{name} must be an integer at least {lower_bound}"
    try:
        value_array = np.asarray(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(message) from exc
    if value_array.shape != () or value_array.dtype == np.bool_:
        raise ValueError(message)
    scalar = value_array.item()
    if isinstance(scalar, (*_BOOL_SCALAR_TYPES, *_TEXT_SCALAR_TYPES)):
        raise ValueError(message)
    if isinstance(scalar, (int, np.integer)):
        parsed = int(scalar)
    elif isinstance(scalar, (float, np.floating)) and float(scalar).is_integer():
        parsed = int(scalar)
    else:
        raise ValueError(message)
    if parsed < lower_bound:
        raise ValueError(message)
    return parsed


def _as_measurement_matrix(measurements: np.ndarray) -> np.ndarray:
    values = np.asarray(measurements, dtype=float)
    if values.ndim != 2:
        raise ValueError(
            "measurements must have shape (num_measurements, measurement_dim)"
        )
    if np.any(~np.isfinite(values)):
        raise ValueError("measurements must contain only finite values")
    return values


def _as_prior_mean(prior_mean: np.ndarray | None, dim: int) -> np.ndarray:
    if prior_mean is None:
        return np.zeros(dim, dtype=float)
    mean = np.asarray(prior_mean, dtype=float)
    if mean.shape != (dim,):
        raise ValueError("prior_mean must have shape (measurement_dim,)")
    if np.any(~np.isfinite(mean)):
        raise ValueError("prior_mean must contain only finite values")
    return mean


def _logsumexp(log_values: np.ndarray) -> float:
    if log_values.size == 0:
        return float("-inf")
    maximum = float(np.max(log_values))
    if not np.isfinite(maximum):
        return maximum
    return maximum + log(float(np.sum(np.exp(log_values - maximum))))


def _isotropic_gaussian_logpdf(
    value: np.ndarray, mean: np.ndarray, variance: float
) -> float:
    residual = value - mean
    dim = value.shape[0]
    return -0.5 * (
        dim * log(2.0 * pi * variance) + float(residual @ residual) / variance
    )


def _posterior_mean_and_variance(
    observation_sum: np.ndarray,
    count: int,
    prior_mean: np.ndarray,
    prior_variance: float,
    measurement_variance: float,
) -> tuple[np.ndarray, float]:
    if count < 0:
        raise ValueError("count must be non-negative")
    posterior_precision = 1.0 / prior_variance + float(count) / measurement_variance
    posterior_variance = 1.0 / posterior_precision
    posterior_mean = posterior_variance * (
        prior_mean / prior_variance + observation_sum / measurement_variance
    )
    return posterior_mean, posterior_variance


@dataclass(frozen=True)
class DPMeasurementSubclusterConfig:
    """Configuration for a conjugate DP-Gaussian subcluster approximation.

    The model assumes target-centered measurements ``y_i`` generated by latent
    subcluster means.  The subcluster mean prior is spherical Gaussian
    ``N(prior_mean, prior_variance I)`` and individual measurements use known
    spherical covariance ``measurement_variance I``.  The Dirichlet-process
    concentration controls the predictive mass assigned to a previously unseen
    subcluster.
    """

    concentration: float = 1.0
    measurement_variance: float = 1.0
    prior_variance: float = 25.0
    prior_mean: np.ndarray | None = None
    max_subclusters: int | None = None

    def __post_init__(self) -> None:
        concentration = _positive_finite_scalar(self.concentration, "concentration")
        measurement_variance = _positive_finite_scalar(
            self.measurement_variance, "measurement_variance"
        )
        prior_variance = _positive_finite_scalar(self.prior_variance, "prior_variance")
        max_subclusters = _integer_at_least(self.max_subclusters, "max_subclusters", 1)
        if self.prior_mean is not None:
            prior_mean = np.asarray(self.prior_mean, dtype=float)
            if prior_mean.ndim != 1:
                raise ValueError("prior_mean must be a one-dimensional vector")
            if np.any(~np.isfinite(prior_mean)):
                raise ValueError("prior_mean must contain only finite values")
            object.__setattr__(self, "prior_mean", prior_mean)
        object.__setattr__(self, "concentration", concentration)
        object.__setattr__(self, "measurement_variance", measurement_variance)
        object.__setattr__(self, "prior_variance", prior_variance)
        object.__setattr__(self, "max_subclusters", max_subclusters)


@dataclass(frozen=True)
class MeasurementSubclusterAtom:
    """Posterior summary for one measurement subcluster."""

    count: int
    empirical_mean: np.ndarray
    posterior_mean: np.ndarray
    posterior_variance: float

    def __post_init__(self) -> None:
        count = _integer_at_least(self.count, "count", 1)
        empirical_mean = np.asarray(self.empirical_mean, dtype=float)
        posterior_mean = np.asarray(self.posterior_mean, dtype=float)
        posterior_variance = _positive_finite_scalar(
            self.posterior_variance, "posterior_variance"
        )
        if empirical_mean.ndim != 1 or posterior_mean.shape != empirical_mean.shape:
            raise ValueError(
                "empirical_mean and posterior_mean must be one-dimensional vectors with the same shape"
            )
        if np.any(~np.isfinite(empirical_mean)):
            raise ValueError("empirical_mean must contain only finite values")
        if np.any(~np.isfinite(posterior_mean)):
            raise ValueError("posterior_mean must contain only finite values")
        object.__setattr__(self, "count", count)
        object.__setattr__(self, "empirical_mean", empirical_mean)
        object.__setattr__(self, "posterior_mean", posterior_mean)
        object.__setattr__(self, "posterior_variance", posterior_variance)


@dataclass(frozen=True)
class DPMeasurementSubclusterResult:
    """Result of greedy DP measurement subclustering."""

    assignments: np.ndarray
    atoms: tuple[MeasurementSubclusterAtom, ...]
    log_predictive_likelihood: float
    responsibilities: np.ndarray

    def __post_init__(self) -> None:
        assignments = np.asarray(self.assignments, dtype=int)
        responsibilities = np.asarray(self.responsibilities, dtype=float)
        if assignments.ndim != 1:
            raise ValueError("assignments must be one-dimensional")
        if responsibilities.ndim != 2:
            raise ValueError("responsibilities must be two-dimensional")
        if responsibilities.shape != (assignments.shape[0], len(self.atoms)):
            raise ValueError(
                "responsibilities must have shape (num_measurements, num_subclusters)"
            )
        if np.any(~np.isfinite(responsibilities)):
            raise ValueError("responsibilities must contain only finite values")
        log_likelihood = _as_finite_scalar(
            self.log_predictive_likelihood, "log_predictive_likelihood"
        )
        object.__setattr__(self, "assignments", assignments)
        object.__setattr__(self, "responsibilities", responsibilities)
        object.__setattr__(self, "log_predictive_likelihood", log_likelihood)

    @property
    def num_subclusters(self) -> int:
        """Return the number of active subclusters."""
        return len(self.atoms)

    @property
    def posterior_means(self) -> np.ndarray:
        """Return posterior atom means with shape ``(num_subclusters, dim)``."""
        if not self.atoms:
            return np.empty((0, 0), dtype=float)
        return np.vstack([atom.posterior_mean for atom in self.atoms])


class _ClusterAccumulator:
    def __init__(self, dim: int) -> None:
        self.count = 0
        self.observation_sum = np.zeros(dim, dtype=float)

    def add(self, measurement: np.ndarray) -> None:
        self.count += 1
        self.observation_sum += measurement

    def posterior_predictive_logpdf(
        self,
        measurement: np.ndarray,
        prior_mean: np.ndarray,
        prior_variance: float,
        measurement_variance: float,
    ) -> float:
        posterior_mean, posterior_variance = _posterior_mean_and_variance(
            self.observation_sum,
            self.count,
            prior_mean,
            prior_variance,
            measurement_variance,
        )
        return _isotropic_gaussian_logpdf(
            measurement,
            posterior_mean,
            measurement_variance + posterior_variance,
        )

    def to_atom(
        self,
        prior_mean: np.ndarray,
        prior_variance: float,
        measurement_variance: float,
    ) -> MeasurementSubclusterAtom:
        posterior_mean, posterior_variance = _posterior_mean_and_variance(
            self.observation_sum,
            self.count,
            prior_mean,
            prior_variance,
            measurement_variance,
        )
        return MeasurementSubclusterAtom(
            count=self.count,
            empirical_mean=self.observation_sum / float(self.count),
            posterior_mean=posterior_mean,
            posterior_variance=posterior_variance,
        )


def fit_dp_measurement_subclusters(
    measurements: np.ndarray,
    config: DPMeasurementSubclusterConfig | None = None,
) -> DPMeasurementSubclusterResult:
    """Greedily partition a measurement subset with a DP-Gaussian prior.

    Parameters
    ----------
    measurements : array-like, shape (num_measurements, measurement_dim)
        Candidate extended-target measurements, usually after subtracting a
        target-state-dependent predicted center or pose.
    config : DPMeasurementSubclusterConfig, optional
        Hyperparameters for the DP prior and Gaussian predictive model.

    Returns
    -------
    DPMeasurementSubclusterResult
        Greedy assignments, posterior atom summaries, active-atom responsibilities,
        and the sequential DP posterior-predictive log likelihood of the subset.
    """
    config = config or DPMeasurementSubclusterConfig()
    values = _as_measurement_matrix(measurements)
    num_measurements, dim = values.shape
    prior_mean = _as_prior_mean(config.prior_mean, dim)

    if num_measurements == 0:
        return DPMeasurementSubclusterResult(
            assignments=np.empty(0, dtype=int),
            atoms=(),
            log_predictive_likelihood=0.0,
            responsibilities=np.empty((0, 0), dtype=float),
        )

    clusters: list[_ClusterAccumulator] = []
    assignments = np.empty(num_measurements, dtype=int)
    log_predictive_likelihood = 0.0

    for measurement_index, measurement in enumerate(values):
        total_count = sum(cluster.count for cluster in clusters)
        denominator = config.concentration + float(total_count)
        log_scores: list[float] = []

        for cluster in clusters:
            log_scores.append(
                log(float(cluster.count))
                - log(denominator)
                + cluster.posterior_predictive_logpdf(
                    measurement,
                    prior_mean,
                    config.prior_variance,
                    config.measurement_variance,
                )
            )

        can_create_new_cluster = (
            config.max_subclusters is None or len(clusters) < config.max_subclusters
        )
        if can_create_new_cluster:
            log_scores.append(
                log(config.concentration)
                - log(denominator)
                + _isotropic_gaussian_logpdf(
                    measurement,
                    prior_mean,
                    config.measurement_variance + config.prior_variance,
                )
            )

        log_score_array = np.asarray(log_scores, dtype=float)
        log_predictive_likelihood += _logsumexp(log_score_array)
        selected = int(np.argmax(log_score_array))
        if selected == len(clusters):
            clusters.append(_ClusterAccumulator(dim))
        clusters[selected].add(measurement)
        assignments[measurement_index] = selected

    atoms = tuple(
        cluster.to_atom(
            prior_mean,
            config.prior_variance,
            config.measurement_variance,
        )
        for cluster in clusters
    )
    responsibilities = active_subcluster_responsibilities(values, atoms, config)
    return DPMeasurementSubclusterResult(
        assignments=assignments,
        atoms=atoms,
        log_predictive_likelihood=log_predictive_likelihood,
        responsibilities=responsibilities,
    )


def active_subcluster_responsibilities(
    measurements: np.ndarray,
    atoms: tuple[MeasurementSubclusterAtom, ...] | list[MeasurementSubclusterAtom],
    config: DPMeasurementSubclusterConfig | None = None,
) -> np.ndarray:
    """Return normalized responsibilities over already-active subclusters.

    This intentionally excludes the residual DP new-subcluster mass.  It is useful
    after fitting when downstream code needs soft assignments for measurements
    inside a candidate target-generated subset.
    """
    config = config or DPMeasurementSubclusterConfig()
    values = _as_measurement_matrix(measurements)
    if len(atoms) == 0:
        return np.empty((values.shape[0], 0), dtype=float)

    counts = np.asarray([atom.count for atom in atoms], dtype=float)
    log_weights = np.log(counts) - log(float(np.sum(counts)))
    log_resp = np.empty((values.shape[0], len(atoms)), dtype=float)
    for measurement_index, measurement in enumerate(values):
        for atom_index, atom in enumerate(atoms):
            log_resp[measurement_index, atom_index] = log_weights[
                atom_index
            ] + _isotropic_gaussian_logpdf(
                measurement,
                atom.posterior_mean,
                config.measurement_variance + atom.posterior_variance,
            )
        row_log_norm = _logsumexp(log_resp[measurement_index])
        log_resp[measurement_index] -= row_log_norm
    return np.exp(log_resp)


def score_dp_measurement_partition(
    measurements: np.ndarray,
    assignments: np.ndarray,
    config: DPMeasurementSubclusterConfig | None = None,
) -> float:
    """Score a fixed sequential partition under the DP-Gaussian predictive model.

    The first occurrence of a label opens a new subcluster; later occurrences of
    the same label are scored as existing-subcluster assignments.  Labels may be
    arbitrary hashable values after conversion by ``np.asarray(assignments)``.
    """
    config = config or DPMeasurementSubclusterConfig()
    values = _as_measurement_matrix(measurements)
    labels = np.asarray(assignments)
    if labels.shape != (values.shape[0],):
        raise ValueError("assignments must have shape (num_measurements,)")
    if values.shape[0] == 0:
        return 0.0

    prior_mean = _as_prior_mean(config.prior_mean, values.shape[1])
    clusters: dict[object, _ClusterAccumulator] = {}
    log_score = 0.0

    for measurement, label in zip(values, labels, strict=True):
        total_count = sum(cluster.count for cluster in clusters.values())
        denominator = config.concentration + float(total_count)
        if label in clusters:
            cluster = clusters[label]
            log_score += (
                log(float(cluster.count))
                - log(denominator)
                + cluster.posterior_predictive_logpdf(
                    measurement,
                    prior_mean,
                    config.prior_variance,
                    config.measurement_variance,
                )
            )
        else:
            if (
                config.max_subclusters is not None
                and len(clusters) >= config.max_subclusters
            ):
                return float("-inf")
            cluster = _ClusterAccumulator(values.shape[1])
            clusters[label] = cluster
            log_score += (
                log(config.concentration)
                - log(denominator)
                + _isotropic_gaussian_logpdf(
                    measurement,
                    prior_mean,
                    config.measurement_variance + config.prior_variance,
                )
            )
        cluster.add(measurement)
    return float(log_score)


def dp_measurement_subset_log_likelihood(
    measurements: np.ndarray,
    config: DPMeasurementSubclusterConfig | None = None,
) -> float:
    """Return a DP-Gaussian log likelihood for one target-generated subset.

    This is the scalar hook that an RFS tracker can use when scoring a candidate
    extended-target measurement cell.  The value is based on the sequential
    posterior-predictive likelihood while the returned partition from
    ``fit_dp_measurement_subclusters`` can be used as a proposal or diagnostic.
    """
    return fit_dp_measurement_subclusters(
        measurements, config
    ).log_predictive_likelihood


__all__ = [
    "DPMeasurementSubclusterConfig",
    "DPMeasurementSubclusterResult",
    "MeasurementSubclusterAtom",
    "active_subcluster_responsibilities",
    "dp_measurement_subset_log_likelihood",
    "fit_dp_measurement_subclusters",
    "score_dp_measurement_partition",
]
