"""
The model package contains filter-independent objects that describe how states
evolve and how measurements are evaluated. These objects are deliberately small
and capability-oriented so filters can opt into the pieces they need.
"""

from ._sampleable_transition_validation import install_sampleable_transition_validation
from ._validated_motion_models import nearly_coordinated_turn_model
from ._validated_sensor_models import install_sensor_state_validation
from .adapters import (
    LinearMeasurementArguments,
    LinearTransitionArguments,
    as_density_transition_model,
    as_likelihood_model,
    as_sampleable_transition_model,
    evaluate_likelihood,
    evaluate_log_likelihood,
    evaluate_transition_density,
    get_optional_model_attribute,
    linear_measurement_arguments,
    linear_transition_arguments,
    predict_distribution_from_model,
    require_model_attribute,
    sample_next_state,
)
from .additive_noise import AdditiveNoiseMeasurementModel, AdditiveNoiseTransitionModel
from .grid import (
    GridLikelihoodMeasurementModel,
    GridTransitionDensityFactoryModel,
    GridTransitionDensityModel,
)
from .likelihood import (
    DensityTransitionModel,
    LikelihoodMeasurementModel,
    SampleableTransitionModel,
    SupportsLikelihood,
    SupportsLogLikelihood,
    SupportsTransitionDensity,
    SupportsTransitionSampling,
)

install_sampleable_transition_validation()
install_sensor_state_validation()

from .linear_gaussian import (
    IdentityGaussianMeasurementModel,
    IdentityGaussianTransitionModel,
    LinearGaussianMeasurementModel,
    LinearGaussianTransitionModel,
)
from .motion_models import (
    constant_acceleration_model,
    constant_acceleration_transition_matrix,
    constant_jerk_model,
    constant_jerk_transition_matrix,
    constant_velocity_model,
    constant_velocity_transition_matrix,
    continuous_to_discrete_lti,
    coordinated_turn_model,
    coordinated_turn_transition,
    integrated_white_noise_covariance,
    kinematic_transition_matrix,
    nearly_constant_speed_model,
    nearly_constant_speed_transition,
    se2_unicycle_model,
    se2_unicycle_transition,
    se3_pose_twist_model,
    se3_pose_twist_transition,
    singer_model,
    singer_process_noise_covariance,
    singer_transition_matrix,
    white_noise_acceleration_covariance,
    white_noise_jerk_covariance,
    white_noise_snap_covariance,
)
from .sensor_models import (
    bearing_only_measurement,
    bearing_only_model,
    camera_projection_measurement,
    camera_projection_model,
    fdoa_measurement,
    fdoa_model,
    radar_range_bearing_doppler_measurement,
    radar_range_bearing_doppler_model,
    range_bearing_jacobian,
    range_bearing_measurement,
    range_bearing_model,
    tdoa_measurement,
    tdoa_model,
)
from .validation import (
    infer_state_dim_from_distribution,
    validate_covariance_matrix,
    validate_matrix,
    validate_measurement_matrix,
    validate_measurement_vector,
    validate_noise_covariance,
    validate_state_vector,
    validate_transition_matrix,
    validate_vector,
)
from .weak_measurement import (
    MaskedLinearMeasurementModel,
    WeakDimensionMeasurementModel,
    block_diag_measurement_covariance,
    diagonal_measurement_covariance,
    masked_position_measurement_model,
    selection_matrix,
    weak_dimension_measurement_model,
)

__all__ = [
    "AdditiveNoiseMeasurementModel",
    "AdditiveNoiseTransitionModel",
    "DensityTransitionModel",
    "GridLikelihoodMeasurementModel",
    "GridTransitionDensityFactoryModel",
    "GridTransitionDensityModel",
    "IdentityGaussianMeasurementModel",
    "IdentityGaussianTransitionModel",
    "LikelihoodMeasurementModel",
    "MaskedLinearMeasurementModel",
    "WeakDimensionMeasurementModel",
    "LinearGaussianMeasurementModel",
    "LinearGaussianTransitionModel",
    "LinearMeasurementArguments",
    "LinearTransitionArguments",
    "SampleableTransitionModel",
    "SupportsLikelihood",
    "SupportsLogLikelihood",
    "SupportsTransitionDensity",
    "SupportsTransitionSampling",
    "bearing_only_measurement",
    "bearing_only_model",
    "camera_projection_measurement",
    "camera_projection_model",
    "constant_acceleration_model",
    "constant_acceleration_transition_matrix",
    "constant_jerk_model",
    "constant_jerk_transition_matrix",
    "constant_velocity_model",
    "constant_velocity_transition_matrix",
    "continuous_to_discrete_lti",
    "coordinated_turn_model",
    "coordinated_turn_transition",
    "fdoa_measurement",
    "fdoa_model",
    "integrated_white_noise_covariance",
    "kinematic_transition_matrix",
    "nearly_constant_speed_model",
    "nearly_constant_speed_transition",
    "nearly_coordinated_turn_model",
    "radar_range_bearing_doppler_measurement",
    "radar_range_bearing_doppler_model",
    "range_bearing_jacobian",
    "range_bearing_measurement",
    "range_bearing_model",
    "se2_unicycle_model",
    "se2_unicycle_transition",
    "se3_pose_twist_model",
    "se3_pose_twist_transition",
    "singer_model",
    "singer_process_noise_covariance",
    "singer_transition_matrix",
    "tdoa_measurement",
    "tdoa_model",
    "white_noise_acceleration_covariance",
    "white_noise_jerk_covariance",
    "white_noise_snap_covariance",
    "as_density_transition_model",
    "block_diag_measurement_covariance",
    "as_likelihood_model",
    "as_sampleable_transition_model",
    "diagonal_measurement_covariance",
    "evaluate_likelihood",
    "evaluate_log_likelihood",
    "evaluate_transition_density",
    "get_optional_model_attribute",
    "infer_state_dim_from_distribution",
    "linear_measurement_arguments",
    "masked_position_measurement_model",
    "linear_transition_arguments",
    "predict_distribution_from_model",
    "require_model_attribute",
    "sample_next_state",
    "selection_matrix",
    "validate_covariance_matrix",
    "validate_matrix",
    "validate_measurement_matrix",
    "validate_measurement_vector",
    "validate_noise_covariance",
    "validate_state_vector",
    "validate_transition_matrix",
    "validate_vector",
    "weak_dimension_measurement_model",
]
