"""Public filter exports.

The filter namespace is intentionally lazy. Importing ``pyrecest.filters`` or a
small baseline filter such as :class:`KalmanFilter` should not import advanced
trackers, plotting helpers, or optional-domain modules. This keeps the public API
convenient while reducing import-time coupling between the baseline package and
heavier research features.
"""

from __future__ import annotations

from importlib import import_module
from typing import Final

_FILTER_EXPORTS: Final[dict[str, str]] = {
    "AbstractAxialFilter": ".abstract_axial_filter",
    "AbstractDummyFilter": ".abstract_dummy_filter",
    "AxialKalmanFilter": ".axial_kalman_filter",
    "AbstractExtendedObjectTracker": ".abstract_extended_object_tracker",
    "AbstractFilter": ".abstract_filter",
    "AbstractFilterManifoldMixin": ".manifold_mixins",
    "AbstractGridFilter": ".abstract_grid_filter",
    "AbstractHypersphereSubsetFilter": ".manifold_mixins",
    "AbstractMultipleExtendedObjectTracker": ".abstract_multiple_extended_object_tracker",
    "AbstractMultitargetTracker": ".abstract_multitarget_tracker",
    "AbstractNearestNeighborTracker": ".abstract_nearest_neighbor_tracker",
    "AbstractParticleFilter": ".abstract_particle_filter",
    "AbstractTrackerWithLogging": ".abstract_tracker_with_logging",
    "AssociationHypothesis": ".association_hypotheses",
    "AdaptiveProcessNoiseConfig": ".adaptive_process_noise",
    "OnlineTimeOffsetEstimator": ".online_time_offset_estimator",
    "RollingNISAdaptiveProcessNoise": ".adaptive_process_noise",
    "SequenceAssociationNode": ".sequence_node_validation",
    "SequenceAssociationPath": ".sequence_association",
    "SequenceTransitionContext": ".sequence_association",
    "WeightedGaussianHypothesis": ".gaussian_hypothesis_mixture",
    "adaptive_process_noise_scale_from_nis_ratio": ".adaptive_process_noise",
    "moment_match_gaussian_hypotheses": ".gaussian_hypothesis_mixture",
    "normalize_log_weights": ".gaussian_hypothesis_mixture",
    "solve_top_k_viterbi_sequence_associations": ".sequence_association",
    "solve_viterbi_sequence_association": ".sequence_association",
    "AssociationResult": ".track_manager",
    "BinghamFilter": ".bingham_filter",
    "BlockParticleFilter": ".block_particle_filter",
    "contiguous_partition": ".block_particle_filter",
    "BoxParticleFilter": ".euclidean_box_particle_filter",
    "BoxedParticleFilter": ".euclidean_boxed_particle_filter",
    "CircularFilterMixin": ".manifold_mixins",
    "CircularFourierFilter": ".circular_fourier_filter",
    "CircularParticleFilter": ".circular_particle_filter",
    "CircularUKF": ".circular_ukf",
    "CostThresholdGate": ".association_hypotheses",
    "DiscreteForwardBackwardResult": ".discrete_state",
    "DiscreteIMMForwardBackwardResult": ".discrete_state",
    "DaumHuangParticleFlowFilter": ".daum_huang_particle_filter",
    "discrete_forward_backward": ".discrete_state",
    "discrete_forward_backward_time_varying": ".discrete_state",
    "edh_particle_flow": ".daum_huang_particle_filter",
    "imm_forward_backward": ".discrete_state",
    "mode_transition_matrix": ".discrete_state",
    "probabilities_to_log_probabilities": ".discrete_state",
    "scaled_emissions": ".discrete_state",
    "SparseTransitionRowCache": ".sparse_transition_cache",
    "cached_sparse_transition_rows": ".sparse_transition_cache",
    "sparse_gaussian_transition_matrix": ".discrete_state",
    "sticky_mode_transition_matrix": ".discrete_state",
    "uniform_log_probabilities": ".discrete_state",
    "uniform_probabilities": ".discrete_state",
    "SparsePairInitializer": ".sparse_second_order_grid",
    "SparsePairTransitionCacheKeyBuilder": ".sparse_second_order_grid",
    "SparsePairTransitionRowBuilder": ".sparse_second_order_grid",
    "SparseSecondOrderGridResult": ".sparse_second_order_grid",
    "SparseTransitionRows": ".sparse_second_order_grid",
    "sparse_second_order_grid_evidence": ".sparse_second_order_grid",
    "DecorrelatedSCGPTracker": ".gprhm_tracker",
    "DecorrelatedScGpTracker": ".gprhm_tracker",
    "EKFSplineTracker": ".ekf_spline_tracker",
    "EkfSplineTracker": ".ekf_spline_tracker",
    "EuclideanBoxParticleFilter": ".euclidean_box_particle_filter",
    "EuclideanBoxedParticleFilter": ".euclidean_boxed_particle_filter",
    "EuclideanFilterMixin": ".manifold_mixins",
    "EuclideanParticleFilter": ".euclidean_particle_filter",
    "EDHParticleFlowFilter": ".daum_huang_particle_filter",
    "FactorizedGIWRMTracker": ".factorized_giw_random_matrix_tracker",
    "FactorizedGIWRandomMatrixTracker": ".factorized_giw_random_matrix_tracker",
    "FejerIdentityFilter": ".fejer_identity_filter",
    "FullSCGPTracker": ".gprhm_tracker",
    "EOTOV0Tracker": ".orientation_vector_eot_tracker",
    "EOTOVTracker": ".orientation_vector_eot_tracker",
    "ExtendedObjectAssociationResult": ".abstract_multiple_extended_object_tracker",
    "ExtendedObjectEstimate": ".abstract_multiple_extended_object_tracker",
    "FixedLagBuffer": ".out_of_sequence",
    "FourierRHMTracker": ".fourier_rhm_tracker",
    "GaussianParticleFlowInfo": ".daum_huang_particle_filter",
    "GoalConditionedReplayIMMFilter": ".goal_conditioned_replay_imm_filter",
    "GoalConditionedReplayParticleFilter": ".goal_conditioned_replay_particle_filter",
    "GoalConditionedReplayParticleIMMFilter": ".goal_conditioned_replay_particle_imm_filter",
    "ReplayGridLikelihoodLookup": ".replay_grid_likelihood",
    "GGIWTracker": ".ggiw_tracker",
    "GlobalNearestNeighbor": ".global_nearest_neighbor",
    "JPDAF": ".joint_probabilistic_data_association_filter",
    "JointProbabilisticDataAssociationFilter": ".joint_probabilistic_data_association_filter",
    "IMM": ".interacting_multiple_model_filter",
    "InteractingMultipleModelFilter": ".interacting_multiple_model_filter",
    "GPRHMTracker": ".gprhm_tracker",
    "HypercylindricalFilterMixin": ".manifold_mixins",
    "HypercylindricalParticleFilter": ".hypercylindrical_particle_filter",
    "HyperhemisphereCartProdParticleFilter": ".hyperhemisphere_cart_prod_particle_filter",
    "HyperhemisphericalFilterMixin": ".manifold_mixins",
    "HyperhemisphericalGridFilter": ".hyperhemispherical_grid_filter",
    "HyperhemisphericalParticleFilter": ".hyperhemispherical_particle_filter",
    "HypersphericalDummyFilter": ".hyperspherical_dummy_filter",
    "HypersphericalFilterMixin": ".manifold_mixins",
    "HypersphericalParticleFilter": ".hyperspherical_particle_filter",
    "HypersphericalUKF": ".hyperspherical_ukf",
    "HypertoroidalDummyFilter": ".hypertoroidal_dummy_filter",
    "HypertoroidalFilterMixin": ".manifold_mixins",
    "HypertoroidalFourierFilter": ".hypertoroidal_fourier_filter",
    "HypertoroidalParticleFilter": ".hypertoroidal_particle_filter",
    "IteratedBatchMEMQKFTracker": ".iterated_batch_mem_qkf_tracker",
    "IteratedBatchMemQkfTracker": ".iterated_batch_mem_qkf_tracker",
    "KalmanFilter": ".kalman_filter",
    "UnscentedKalmanFilter": ".unscented_kalman_filter",
    "UKFOnManifolds": ".ukf_on_manifolds",
    "KernelSMEFilter": ".kernel_sme_filter",
    "LinBoundedFilterMixin": ".manifold_mixins",
    "LinBoundedParticleFilter": ".lin_bounded_particle_filter",
    "LinPeriodicFilterMixin": ".manifold_mixins",
    "LEDHParticleFlowFilter": ".daum_huang_particle_filter",
    "LocalizedDaumHuangParticleFlowFilter": ".daum_huang_particle_filter",
    "LOMEMTracker": ".lomem_tracker",
    "LomemTracker": ".lomem_tracker",
    "BernoulliComponent": ".multi_bernoulli_tracker",
    "MultiBernoulliMixtureHypothesis": ".multi_bernoulli_mixture_tracker",
    "MultiBernoulliMixtureTracker": ".multi_bernoulli_mixture_tracker",
    "ManifoldExponentialMovingAverage": ".manifold_exponential_moving_average",
    "MeasurementRecord": ".out_of_sequence",
    "MeasurementTimeBuffer": ".out_of_sequence",
    "MeasurementUpdateDiagnostics": ".update_diagnostics",
    "MeasurementScore": ".measurement_scoring",
    "MeasurementReliabilitySelection": ".measurement_reliability",
    "normalize_measurement_weights": ".measurement_reliability",
    "normalize_active_measurement_mask": ".measurement_reliability",
    "normalize_measurement_reliability": ".measurement_reliability",
    "normalize_measurement_noise_covariances": ".measurement_reliability",
    "MultiBernoulliTracker": ".multi_bernoulli_tracker",
    "MultiHypothesisTracker": ".multi_hypothesis_tracker",
    "MultipleExtendedObjectStepResult": ".abstract_multiple_extended_object_tracker",
    "LinPeriodicParticleFilter": ".lin_periodic_particle_filter",
    "MEMEKFStarTracker": ".mem_ekf_star_tracker",
    "MEMEKFStarOATracker": ".mem_ekf_star_oa_tracker",
    "MEMEKFTracker": ".mem_ekf_tracker",
    "MEMQKFTracker": ".mem_qkf_tracker",
    "MEMSOEKFTracker": ".mem_soekf_tracker",
    "NearestNeighborMultiBernoulliTracker": ".multi_bernoulli_mixture_tracker",
    "MemEkfStarTracker": ".mem_ekf_star_tracker",
    "MemEkfStarOATracker": ".mem_ekf_star_oa_tracker",
    "MemEkfTracker": ".mem_ekf_tracker",
    "MemQkfTracker": ".mem_qkf_tracker",
    "MemSoekfTracker": ".mem_soekf_tracker",
    "ModeRBPFManifoldUKF": ".mode_rbpf_manifold_ukf_tracker",
    "ModeRBPFManifoldUKFTracker": ".mode_rbpf_manifold_ukf_tracker",
    "ModeRbpfManifoldUkfTracker": ".mode_rbpf_manifold_ukf_tracker",
    "NISGate": ".association_hypotheses",
    "OrientationAwareVBRMTracker": ".vbrm_o_tracker",
    "OrientationAwareVbrmTracker": ".vbrm_o_tracker",
    "OrientationVectorEOT0Tracker": ".orientation_vector_eot_tracker",
    "OrientationVectorEOTTracker": ".orientation_vector_eot_tracker",
    "OutOfSequenceKalmanUpdater": ".out_of_sequence",
    "OutOfSequenceParticleUpdater": ".out_of_sequence",
    "OutOfSequenceResult": ".out_of_sequence",
    "PartitionedSO3ProductParticleFilter": ".partitioned_so3_product_particle_filter",
    "PiecewiseConstantFilter": ".piecewise_constant_filter",
    "ProbabilityThresholdGate": ".association_hypotheses",
    "RandomMatrixTracker": ".random_matrix_tracker",
    "SCGPTracker": ".gprhm_tracker",
    "ScGpTracker": ".gprhm_tracker",
    "SCGPContourSample": ".gprhm_tracker",
    "SurvivalAwareAssociationConfig": ".survival_aware_association",
    "TimestampedItem": ".out_of_sequence",
    "TopKGate": ".association_hypotheses",
    "VelocityAlignedMEMEKFStarTracker": ".mem_ekf_star_oa_tracker",
    "VelocityAlignedMemEkfStarTracker": ".mem_ekf_star_oa_tracker",
    "VelocityLockedMEMQKFTracker": ".velocity_locked_mem_qkf_tracker",
    "VelocityLockedMemQkfTracker": ".velocity_locked_mem_qkf_tracker",
    "VBRMOTracker": ".vbrm_o_tracker",
    "VBRMTracker": ".vbrm_tracker",
    "VbrmOTracker": ".vbrm_o_tracker",
    "VbrmTracker": ".vbrm_tracker",
    "association_result_from_hypotheses": ".association_hypotheses",
    "adaptive_position_proposal_probability": ".replay_grid_likelihood",
    "apply_survival_aware_prior_to_hypotheses": ".survival_aware_association",
    "build_replay_grid_likelihood_lookup": ".replay_grid_likelihood",
    "build_survival_aware_linear_gaussian_hypothesis_associator": ".survival_aware_association",
    "effective_sample_size_fraction": ".replay_grid_likelihood",
    "grid_proposal_weights": ".replay_grid_likelihood",
    "gaussian_bridge_moments": ".daum_huang_particle_filter",
    "gaussian_flow_affine_increment": ".daum_huang_particle_filter",
    "gaussian_particle_flow_drift": ".daum_huang_particle_filter",
    "gaussian_particle_flow_update": ".daum_huang_particle_filter",
    "ledh_particle_flow": ".daum_huang_particle_filter",
    "particle_position_log_posterior": ".replay_grid_likelihood",
    "replay_grid_log_likelihood_values": ".replay_grid_likelihood",
    "update_position_grid_likelihood": ".replay_grid_likelihood",
    "build_global_nearest_neighbor_associator": ".track_manager",
    "build_kalman_measurement_initiator": ".track_manager",
    "build_linear_gaussian_hypothesis_associator": ".association_hypotheses",
    "build_linear_gaussian_predictor": ".track_manager",
    "build_linear_gaussian_updater": ".track_manager",
    "filter_hypotheses": ".association_hypotheses",
    "gate_hypotheses": ".association_hypotheses",
    "hypotheses_to_cost_matrix": ".association_hypotheses",
    "hypotheses_to_log_likelihood_matrix": ".association_hypotheses",
    "hypotheses_to_probability_matrix": ".association_hypotheses",
    "hypothesis_cost": ".association_hypotheses",
    "infer_hypothesis_shape": ".association_hypotheses",
    "linear_gaussian_association_hypotheses": ".association_hypotheses",
    "missed_detection_hypothesis": ".association_hypotheses",
    "quaternion_grid_transition_density": ".so3_grid_transition",
    "Track": ".track_manager",
    "TrackManager": ".track_manager",
    "TrackManagerStepResult": ".track_manager",
    "TrackStatus": ".track_manager",
    "solve_global_nearest_neighbor": ".track_manager",
    "student_t_covariance_scale": "._linear_gaussian",
    "retrodict_linear_gaussian": ".out_of_sequence",
    "retrodict_linear_gaussian_state": ".out_of_sequence",
    "resolve_partition": ".block_particle_filter",
    "SE2FilterMixin": ".manifold_mixins",
    "SE2UKF": ".se2_ukf",
    "SO3ProductBlockParticleFilter": ".partitioned_so3_product_particle_filter",
    "SO3ProductSequenceFilterRunner": ".so3_product_sequence_filter",
    "SO3ProductParticleFilter": ".so3_product_particle_filter",
    "so3_right_multiplication_grid_transition": ".so3_grid_transition",
    "run_so3_product_particle_filter_sequence": ".so3_product_sequence_filter",
    "run_so3_product_sequence_filter": ".so3_product_sequence_filter",
    "SphericalHarmonicsEOTTracker": ".spherical_harmonics_eot_tracker",
    "SphericalHarmonicsExtendedObjectTracker": ".spherical_harmonics_eot_tracker",
    "StateSpaceSubdivisionFilter": ".state_space_subdivision_filter",
    "survival_aware_linear_gaussian_association_hypotheses": ".survival_aware_association",
    "survival_aware_missed_detection_costs": ".survival_aware_association",
    "survival_aware_track_log_prior": ".survival_aware_association",
    "survival_aware_unassigned_measurement_cost": ".survival_aware_association",
    "ToroidalFilterMixin": ".manifold_mixins",
    "ToroidalParticleFilter": ".toroidal_particle_filter",
    "ToroidalWrappedNormalFilter": ".toroidal_wrapped_normal_filter",
    "validate_partition": ".block_particle_filter",
    "VonMisesFilter": ".von_mises_filter",
    "VonMisesFisherFilter": ".von_mises_fisher_filter",
    "WrappedNormalFilter": ".wrapped_normal_filter",
}

__all__ = tuple(_FILTER_EXPORTS)


def __getattr__(name: str):
    """Resolve public filter symbols lazily on first access."""
    try:
        module_name = _FILTER_EXPORTS[name]
    except KeyError as exc:  # pragma: no cover - normal attribute protocol
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__():
    """List lazily exported filter symbols for interactive use."""
    return sorted(set(globals()) | set(_FILTER_EXPORTS))
